
CREATE TABLE USERLOGINS (
	    USERNAME varchar(50) NOT NULL,
	    PASSWORD varchar(50) NOT NULL,
	    
	    PRIMARY KEY (USERNAME)
    
);

CREATE TABLE ADDRESS (
		ADDRESSNAME varchar(255) NOT NULL,
	    OCCUPATION varchar(255) NOT NULL,
	    STREETNAME varchar(255) NOT NULL,
		STATEAREADISTRICT varchar(255) NOT NULL,
	    CITYTOWNVILLAGE varchar(255) NOT NULL,
		PROVINCE varchar(255) NOT NULL,
	    POSTALCODE varchar(255) NOT NULL,
		COUNTRY varchar(255) NOT NULL,
		UID varchar(255) NOT NULL,
	   
	    PRIMARY KEY (ADDRESSNAME)
);

CREATE TABLE IDENTITIES
    ( ID INT NOT NULL GENERATED ALWAYS AS IDENTITY
    	CONSTRAINT IDENTITY_PK PRIMARY KEY, 
       	DISPLAY_NAME VARCHAR(255),        
    	EMAIL VARCHAR(255),
    	UID VARCHAR(255)NOT NULL
    
    
    );
    
    INSERT INTO USERLOGINS (USERNAME, PASSWORD)
	VALUES ('kabirou', '2018');
    
	SELECT * FROM IDENTITIES;
     